version: '3'
services:
  mysql57:
    image: "mysql:5.7"
    ports:
     - "3306:3306"
    volumes:
     - "mysql57-data:/var/lib/mysql"
    environment:
     - MYSQL_ROOT_PASSWORD=root
    command: mysqld --lower_case_table_names=1 --skip-ssl

volumes:
  mysql57-data:
    driver: local