version: '3'

services:
  dotzapi:
    build:      
      context: .
      dockerfile: ./Dotz.Api/Dockerfile
    container_name: dotzapi
    environment:
      ASPNETCORE_ENVIRONMENT: 'Staging'
    ports:
      - "56000:80"
     # - "3308:3308"